/* -- Inserts de usuários -- */
INSERT INTO USERS (FIRST_NAME, LAST_NAME) VALUES ('admin', 'admin');

/* -- Inserts de produtos -- */
INSERT INTO PRODUCT (DESCRIPTION, PRODUCT_TYPE, SUPPLIER_PRICE, AMOUNT) VALUES ('TV', 'E', 1400, 6);
INSERT INTO PRODUCT (DESCRIPTION, PRODUCT_TYPE, SUPPLIER_PRICE, AMOUNT) VALUES ('Computador', 'E', 2000, 3);
INSERT INTO PRODUCT (DESCRIPTION, PRODUCT_TYPE, SUPPLIER_PRICE, AMOUNT) VALUES ('Sofa', 'M', 500, 12);
INSERT INTO PRODUCT (DESCRIPTION, PRODUCT_TYPE, SUPPLIER_PRICE, AMOUNT) VALUES ('Mesa', 'M', 100, 2);
INSERT INTO PRODUCT (DESCRIPTION, PRODUCT_TYPE, SUPPLIER_PRICE, AMOUNT) VALUES ('Cadeira', 'M', 20, 60);